package com.privatesolarmon.app.bms

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * Modbus-RTU + Solarman V5 codecs, pinned to reference frames generated by the real
 * pysolarmanv5 library (logger serial 1234567890, sequence 0x5A).
 */
class InverterProtocolTest {

    private fun bytes(hex: String) = requireNotNull(hex.hexToBytesOrNull())

    @Test
    fun buildsModbusReadRequest() {
        // read holding 0x0100 ×1, slave 1  ->  01 03 01 00 00 01 + CRC(85 f6)
        assertEquals("01030100000185f6", ModbusRtu.readHoldingRegisters(1, 0x0100, 1).toHex(""))
    }

    @Test
    fun parsesModbusResponse() {
        val regs = ModbusRtu.parseHoldingResponse(bytes("0103020054b9bb"), 1)
        assertNotNull(regs)
        assertEquals(1, regs!!.size)
        assertEquals(0x0054, regs[0]) // 84
    }

    @Test
    fun rejectsModbusBadCrc() {
        assertNull(ModbusRtu.parseHoldingResponse(bytes("0103020054b9bc"), 1))
    }

    @Test
    fun rejectsModbusWrongSlave() {
        assertNull(ModbusRtu.parseHoldingResponse(bytes("0103020054b9bb"), 0xFF))
    }

    @Test
    fun encodesV5RequestLikeLibrary() {
        val frame = SolarmanV5.encode(1234567890L, 0x5A, bytes("01030100000185f6"))
        assertEquals(
            "a5170010455a00d202964902000000000000000000000000000001030100000185f6fc15",
            frame.toHex(""),
        )
    }

    @Test
    fun decodesV5ResponseToModbus() {
        val resp = bytes("a5150010155a00d202964902010000000000000000000000000103020054b9bb1815")
        val modbus = SolarmanV5.decode(resp)
        assertNotNull(modbus)
        assertEquals("0103020054b9bb", modbus!!.toHex(""))
    }

    @Test
    fun fullRoundTripToRegisterValue() {
        // decode V5 -> parse Modbus -> register value
        val resp = bytes("a5150010155a00d202964902010000000000000000000000000103020054b9bb1815")
        val modbus = SolarmanV5.decode(resp)!!
        val regs = ModbusRtu.parseHoldingResponse(modbus, 1)!!
        assertEquals(84, regs[0])
    }

    @Test
    fun srneDecodeScalesValues() {
        val s = SrneInverter.decode(
            mapOf(
                0x0100 to 84,       // SOC 84%
                0x0101 to 533,      // 53.3 V
                0x0102 to 0xFFCE,   // raw -50; this unit reports +discharge/-charge, so negate -> +5.0 A (charge)
                0x0107 to 1816,     // PV1 181.6 V
                0x0108 to 112,      // PV1 11.2 A
                0x010F to 1100,     // PV2 110.0 V
                0x0110 to 120,      // PV2 12.0 A
                0x021B to 640,      // 640 W load L1
                0x0232 to 610,      // 610 W load L2
            ),
        )
        assertEquals(84, s.batterySoc)
        assertEquals(53.3, s.batteryVoltage!!, 1e-9)
        assertEquals(5.0, s.batteryCurrent!!, 1e-9) // negated: raw -50 -> +5.0 A charging
        assertEquals(181.6, s.pv1Voltage!!, 1e-9)
        assertEquals(11.2, s.pv1Current!!, 1e-9)
        assertEquals(110.0, s.pv2Voltage!!, 1e-9)
        assertEquals(12.0, s.pv2Current!!, 1e-9)
        assertEquals(181.6 * 11.2 + 110.0 * 12.0, s.pvPower!!, 1e-9) // total PV = both strings
        assertEquals(640, s.loadPower)
        assertEquals(610, s.loadL2Power)
        assertEquals(1250, s.loadTotal) // L1 + L2
    }

    @Test
    fun batteryCurrentSignIsNormalisedToChargePositive() {
        // 0x0102 reads positive while physically discharging (load > PV); after normalising,
        // current and derived power must be negative so the UI shows "discharging".
        val s = SrneInverter.decode(mapOf(0x0101 to 528, 0x0102 to 166)) // 52.8 V, raw +16.6 A
        assertEquals(-16.6, s.batteryCurrent!!, 1e-9)
        assertEquals(52.8 * -16.6, s.batteryPower!!, 1e-9) // negative -> discharging
    }

    @Test
    fun loadTotalFallsBackToSingleLegWhenL2Missing() {
        val s = SrneInverter.decode(mapOf(0x021B to 700)) // only L1 present
        assertEquals(700, s.loadTotal)
    }

    @Test
    fun hasCoreRejectsPartialOrZeroReads() {
        assertEquals(false, SrneInverter.hasCore(emptyMap()))              // nothing came back
        assertEquals(false, SrneInverter.hasCore(mapOf(0x0232 to 610)))    // only an L2 block
        assertEquals(false, SrneInverter.hasCore(mapOf(0x0101 to 0)))      // pack voltage 0 = bogus
        assertEquals(true, SrneInverter.hasCore(mapOf(0x0101 to 528)))     // real 52.8 V pack
    }

    @Test
    fun decodesActiveFaultCodesAndMachineState() {
        val s = SrneInverter.decode(mapOf(0x0101 to 528, 0x0204 to 8, 0x0205 to 14, 0x0206 to 0, 0x0210 to 6))
        assertEquals(listOf(8, 14), s.faultCodes) // non-zero codes only
        assertEquals(true, s.hasFault)
        assertEquals(6, s.machineState)
    }

    @Test
    fun noFaultWhenCodeRegistersAreZeroOrAbsent() {
        assertEquals(false, SrneInverter.decode(mapOf(0x0101 to 528, 0x0204 to 0)).hasFault)
        assertEquals(false, SrneInverter.decode(mapOf(0x0101 to 528)).hasFault)
    }

    @Test
    fun mergeCarriesForwardBlocksMissingFromAPartialRead() {
        // A good full reading, then a poll that only returned the battery+PV block.
        val previous = mapOf(
            0x0100 to 84, 0x0101 to 528, 0x0102 to 100,
            0x021B to 700, 0x0232 to 610, // load L1 + L2
        )
        val freshPartial = mapOf(0x0100 to 81, 0x0101 to 521, 0x0102 to 120) // load blocks dropped

        val merged = SrneInverter.merge(previous, freshPartial)
        val s = SrneInverter.decode(merged)

        assertEquals(81, s.batterySoc)            // fresh value wins
        assertEquals(52.1, s.batteryVoltage!!, 1e-9)
        assertEquals(1310, s.loadTotal)           // L1+L2 carried forward, not blanked to 0
    }
}
